# Generated by Django 5.1.2 on 2024-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('carro', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
