# Generated by Django 5.1.2 on 2024-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='servicos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='carro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='cor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
