# Generated by Django 5.1.5 on 2025-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order_register', '0003_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
