# Generated by Django 4.1.13 on 2024-10-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('carro', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
