# Generated by Django 5.1.5 on 2025-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
